"""empty message

Revision ID: 3075612cb806
Revises: 
Create Date: 2023-12-15 21:58:10.128497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3075612cb806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('compania_local',
               existing_type=sa.BLOB(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('compania_local',
               existing_type=sa.Integer(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
